### ISSUE TITLE
UI design implementation

### ISSUE THREAD

**Issue by milad-aleali** [Reainheart/CST316JP#60]
Tasks from Milad
- [x] Add styling to the selection tool on node select
- [x] Header's styling needs to be re-done
- [x] More black/dark blue/purple colors to be more in line with the canvas and nodes
- [ ] Code/Memory/Functions Views styling should be re-done
- [ ] Take out the gray and white colors 
- [ ] More darker colors to be more in-line with the rest of the page
- [ ] The two scroll bars on the right and bottom of the screen must be taken out
- [ ] The Code/Memory/Functions View column is no longer being moved by toolbar
- [x]  Add styling to the selection tool on node select

### Tasks from Noah
- [ ]  Header's styling needs to be re-done
- [ ]  More black/dark blue/purple colors to be more in line with the canvas and nodes
- [ ]  Code/Memory/Functions Views styling should be re-done
- [ ]  Take out the gray and white colors
- [ ]  More darker colors to be more in-line with the rest of the page
- [ ]  The two scroll bars on the right and bottom of the screen must be taken out
- [ ]  The Code/Memory/Functions View column is no longer being moved by toolbar
- [x]  Add styling to the learn page

**Comment by Reainheart** [comment]
- [ ] Integrate Toolbar into the overall design
- [ ] Left anchor the Nav Bar links
- [ ] Implement the light and dark mode color scheme
- [ ] differentiate the Canvas from the toolbar and Code view
- [ ] Implement Array Styling
- [ ] Implement Node Styling

**Comment by Reainheart** [comment]
> * [x]  Add styling to the selection tool on node select
> * [x]  Header's styling needs to be re-done
> * [x]  More black/dark blue/purple colors to be more in line with the canvas and nodes
> * [ ]  Code/Memory/Functions Views styling should be re-done
> * [ ]  Take out the grey and white colors
> * [ ]  More darker colors to be more in-line with the rest of the page
> * [ ]  The two scroll bars on the right and bottom of the screen must be taken out
> * [ ]  The Code/Memory/Functions View column is no longer being moved by toolbar
> * [x]  Add styling to the learn page
