### ISSUE TITLE
Implement Logic for tracking nodes and pointers that creates a Tree

### ISSUE THREAD

**Issue by Reainheart** [Reainheart/CST316JP#77]
- [x] Draws the starting three nodes 
    - [x] Draws the head 
    - [x] Draws the 'value dummy' 
    - [x] Draws the tail
- [x] Draws pointers between each node
- [x] Updates canvas
- [x] Removes using the selection menu
- [x] Adheres to selection menu
- [x] Adheres to selection Rules
- [x] Adheres to pointers deletion

**Comment by Reainheart** [comment]
This is working in Dev as of today.
